Permit negative resource IDs
tjhancocks/kdl pull request #1
Opened 2020-04-17 07:38 UTC by bendyer

When compiling `Ship.kdl` the following error is shown:

```$ kdl/bin/kdl -o kdl-out/ kdl-nova/Types/Ship.kdl 
kdl-nova/Types/Ship.kdl:L385:65 - Could not ensure the correctness of the token '1'
```

The issue is with the field specification `DefaultItems<$FieldNumber> as Outfit& = None [ None = #-1 ];`, where a resource ID of `#-1` is used to indicate no value is present.

This change permits negative resource IDs and allows `Ship.kdl` to compile without error.

2020-04-17 15:07 UTC, tjhancocks commented
Good spot. Could you add an example KDL script to demonstrate negative IDs?

For one level of automated testing I plan to create a script that will compile the current KDL, and then throw _all_ of the example scripts at it.

2020-04-17 15:09 UTC, tjhancocks requested changes
Good spot. Could you add an example KDL script to demonstrate negative IDs?

For one level of automated testing I plan to create a script that will compile the current KDL, and then throw all of the example scripts at it.

Edit: Don't worry about whether the resulting 'ndat' file makes sense or not. The tests will be to ensure that KDL is parsing correctly. Not validating output art this time.

2020-04-18 02:48 UTC, bendyer commented
I've added a KDL file demonstrating negative resource IDs; the compiler runs successfully: 

```
$ bin/kdl -o ../kdl-out/ Support/Examples/NegativeResourceIDTest.kdl 
$
```

2020-04-18 04:28 UTC, tjhancocks approved these changes

2020-04-18 04:29 UTC, merged